from typing import Protocol, Optional
from pathlib import Path
from setupdev.core.models import Service

class WorkspaceDriver(Protocol):
    def create_session(self, root_path: Path) -> None: ...
    def create_window(self, service: Service, command: Optional[str] = None) -> None: ...
    def rename_initial_window(self, new_name: str) -> None: ...
    def attach(self) -> None: ...
    def send_command(self, window_name, command) -> None: ...